"""empty message

Revision ID: 34d3dcf45354
Revises: ccd0eb9825d7
Create Date: 2025-09-29 11:36:27.565457

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34d3dcf45354"
down_revision = "ccd0eb9825d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("readinglist_book_id_key"), type_="unique")

    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("recommendations_book_id_key"), type_="unique"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("recommendations_book_id_key"),
            ["book_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("readinglist_book_id_key"),
            ["book_id"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
