"""empty message

Revision ID: 3c1cff6251b8
Revises: ef2b262825b9
Create Date: 2025-10-14 20:58:37.623486

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3c1cff6251b8"
down_revision = "ef2b262825b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("ratings")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ratings", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
