"""empty message

Revision ID: a77a6bdabce4
Revises: b08d32aabae0
Create Date: 2025-09-12 18:22:20.541386

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a77a6bdabce4"
down_revision = "b08d32aabae0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "avatar", existing_type=sa.VARCHAR(length=150), nullable=True
        )
        batch_op.drop_constraint(
            batch_op.f("profiles_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "users", ["id"], ["id"])
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("profiles_user_id_fkey"), "users", ["user_id"], ["id"]
        )
        batch_op.alter_column(
            "avatar", existing_type=sa.VARCHAR(length=150), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    # ### end Alembic commands ###
