"""empty message

Revision ID: d6a4162f1f8a
Revises: 2cf842ff3678
Create Date: 2025-02-24 13:07:20.201598

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6a4162f1f8a"
down_revision = "2cf842ff3678"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.VARCHAR(length=60),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=60),
            type_=sa.VARCHAR(length=50),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
