"""empty message

Revision ID: dadfd71fc0a9
Revises: a77a6bdabce4
Create Date: 2025-09-13 14:59:50.489071

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dadfd71fc0a9"
down_revision = "a77a6bdabce4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("quotes_profile_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "profiles", ["user_id"], ["id"])
        batch_op.drop_column("profile_id")

    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("readinglist_profile_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "profiles", ["user_id"], ["id"])
        batch_op.drop_column("profile_id")

    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("recommendations_profile_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "profiles", ["user_id"], ["id"])
        batch_op.drop_column("profile_id")

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("reviews_profile_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "profiles", ["user_id"], ["id"])
        batch_op.drop_column("profile_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("reviews_profile_id_fkey"), "profiles", ["profile_id"], ["id"]
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("recommendations_profile_id_fkey"),
            "profiles",
            ["profile_id"],
            ["id"],
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("readinglist_profile_id_fkey"),
            "profiles",
            ["profile_id"],
            ["id"],
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("quotes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("quotes_profile_id_fkey"), "profiles", ["profile_id"], ["id"]
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
