"""empty message

Revision ID: e4102c51d216
Revises: dadfd71fc0a9
Create Date: 2025-09-14 19:48:46.573882

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4102c51d216"
down_revision = "dadfd71fc0a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["book_id"])

    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["book_id"])

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["book_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("readinglist", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
